#!/usr/bin/env python

import shutil
from collections import defaultdict, namedtuple
from pathlib import Path
from urllib.parse import urlparse
from subprocess import run
import shlex

git_rev_parse = run(shlex.split('git rev-parse --show-toplevel'), capture_output=True, check=True)
git_root_path = Path(git_rev_parse.stdout.decode().strip())

existing_plugins = set(Path('pack').glob('*/start/*'))

def parse_author(url):
    return str(Path(urlparse(url).path.removeprefix("/")).parent)

pack_dir = Path("pack")
if not pack_dir.exists():
    pack_dir.mkdir()

Plugin = namedtuple('Plugin', ['path', 'url'])

by_author = defaultdict(list)
desired_plugins = set()

for plugin in Path("plugins.txt").read_text().splitlines():
    author, plugin_name = plugin.split('/')
    author_path = pack_dir / author / "start"
    plugin_path = author_path / plugin_name
    plugin_url = (
        urlparse(plugin)
        ._replace(
            scheme="https",
            netloc="github.com",
        )
        .geturl() + ".git"
    )
    by_author[author].append(Plugin(path=plugin_path, url=plugin_url))
    desired_plugins.add(plugin_path)




for author, plugins in by_author.items():

    author_path = pack_dir / author / "start"
    if not author_path.exists():
        author_path.mkdir(parents=True)

    for plugin in plugins:
        if plugin.path not in existing_plugins:
            print(plugin.url, author_path)
            run(["git", "submodule", "add", plugin.url], cwd=author_path)

        # Always generate helptags
        run(
            shlex.split(f'vim -u NONE -c "helptags {plugin.path}/doc" -c q'),
        )

for plugin in existing_plugins - desired_plugins:
    print('removing', plugin)

    run(shlex.split(f'git config -f .git/config --remove-section submodule.{"nvim" / plugin}'), cwd=git_root_path)
    run(['git', 'rm', plugin])

    run(['git', 'add', '.'], cwd=git_root_path)
    run(['git', 'commit', '-m', f'removed {plugin.stem}'], cwd=git_root_path)


    git_module_path = git_root_path / '.git' / 'modules' / 'nvim' / plugin

    if git_module_path.exists():
        shutil.rmtree(git_module_path)

    if not list(plugin.parent.glob('*')):
        shutil.rmtree(plugin.parent.parent)
    if not list(git_module_path.parent.glob('*')):
        shutil.rmtree(git_module_path.parent.parent)
